
# nexus
#@baseUrl = http://ec2-18-237-133-156.us-west-2.compute.amazonaws.com:9200
@baseUrl = http://localhost:9200

###
GET {{baseUrl}}/_cat/indices

###
DELETE {{baseUrl}}/people

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "describe opensearch_dashboards_sample_data_flights "
}

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "source = opensearch_dashboards_sample_data_flights "
}

###
DELETE {{baseUrl}}/test002

###
PUT {{baseUrl}}/test002
Content-Type: application/x-ndjson

{
  "mappings": {
    "properties": {
      "id": {
        "type": "integer"
      },
      "salary": {
        "type": "integer"
      }
    }
  }
}

###
POST {{baseUrl}}/_bulk/
Content-Type: application/x-ndjson

{"index": {"_index": "test002"}}
{"id": 1000, "salary": 100000}
{"index": {"_index": "test002"}}
{"id": 1001}

###
DELETE  {{baseUrl}}/test001

###
PUT {{baseUrl}}/test001
Content-Type: application/x-ndjson

{
  "mappings": {
    "properties": {
      "profile": {
        "type": "object",
        "dynamic": false
      }
    }
  }
}

###
POST {{baseUrl}}/_bulk/
Content-Type: application/x-ndjson

{"index": {"_index": "test001"}}
{"profile": {"age": 1}}
{"index": {"_index": "test001"}}
{"profile": {"address": "a"}}

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "source = test002"
}

###
GET {{baseUrl}}/test001/_search




###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "source = test002 | fields salary "
}

###
DELETE {{baseUrl}}/people

###
PUT {{baseUrl}}/people
Content-Type: application/x-ndjson

{
  "mappings": {
    "properties": {
      "city": {
        "properties": {
          "name": {
            "type": "keyword"
          },
          "location": {
            "properties": {
              "latitude": {
                "type": "double"
              }
            }
          }
        }
      },
      "account": {
        "properties": {
          "id": {
            "type": "keyword"
          }
        }
      },
      "projects": {
        "type": "nested",
        "properties": {
          "name": {
            "type": "keyword"
          }
        }
      }
    }
  }
}


###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "describe people"
}


###
POST {{baseUrl}}/_bulk/
Content-Type: application/x-ndjson

{"index": {"_index": "people"}}
{"@timestamp": 1718458823000, "id": 1000, "name": "Jake", "occupation": "Engineer", "country": "USA", "salary": 100000}
{"index": {"_index": "people"}}
{"@timestamp": 1718458833000, "id": 1001, "name": "Hello", "occupation": "Artist", "country": "USA ABC", "salary": 70000}
{"index": {"_index": "people"}}
{"@timestamp": 1718458843000, "id": 1002, "name": "John", "occupation": "Doctor", "country": "usa", "salary": 120000}
{"index": {"_index": "people"}}
{"@timestamp": 1718458843000, "id": 1002, "name": "John", "occupation": "Doctor", "country": "China", "salary": 120000}

###
POST {{baseUrl}}/people/_search
Content-Type: application/x-ndjson

{
  "query": {
    "bool": {
      "must_not": {
        "match": {
          "country": "USA"
        }
      }
    }
  }
}


###
POST {{baseUrl}}/people/_search
Content-Type: application/x-ndjson

{
  "query": {
    "match": {
        "country": "USA"
    }
  }
}

###
POST {{baseUrl}}/people/_search
Content-Type: application/x-ndjson

{
  "query": {
    "term": {
        "country": "USA"
    }
  }
}

###
PUT {{baseUrl}}/

###
DELETE {{baseUrl}}/idx00003

###
PUT {{baseUrl}}/idx00003
Content-Type: application/x-ndjson

{
  "mappings": {
    "properties": {
      "timestamp": {
        "type":   "date",
        "format": "yyyy-MM-dd-HH-mm-ss || epoch_millis"
      }
    }
  }
}

###
POST {{baseUrl}}/_bulk/
Content-Type: application/x-ndjson

{"index": {"_index": "idx00003"}}
{"timestamp": "2015-01-01 12:10:30"}

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "source = idx00003 | where timestamp >= '2024-03-27 00:00:00' and timestamp <= '2024-04-01 16:39:38'"
}

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "source = idx00003 "
}

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
  "query": "source = idx00003 | fields timestamp"
}

###
POST {{baseUrl}}/idx00003/_search
Content-Type: application/x-ndjson

{"from":0,"size":10000,"timeout":"1m","query":{"bool":{"filter":[{"range":{"timestamp":{"from":"20240126","to":null,"include_lower":true,"include_upper":true,"boost":1.0}}},{"range":{"timestamp":{"from":null,"to":"20240331","include_lower":true,"include_upper":true,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":["timestamp"],"excludes":[]},"sort":[{"_doc":{"order":"asc"}}]}

###
POST {{baseUrl}}/idx00003/_search
Content-Type: application/x-ndjson


###
POST {{baseUrl}}/idx00003/_search
Content-Type: application/x-ndjson

{
  "from": 0,
  "size": 10000,
  "timeout": "1m",
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "timestamp": {
              "from": "2024-03-26 00:00:00",
              "to": null,
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
      "timestamp"
    ],
    "excludes": []
  },
  "sort": [
    {
      "_doc": {
        "order": "asc"
      }
    }
  ]
}

###
POST {{baseUrl}}/idx00003/_search
Content-Type: application/x-ndjson

{
  "script_fields": {
    "timestamp_epoch": {
      "script": {
        "source": "doc['timestamp'].value.toInstant().toEpochMilli()"
      }
    }
  },
  "fields": ["timestamp"]
}



###
PUT {{baseUrl}}/sample-index
Content-Type: application/x-ndjson

{
  "mappings": {
    "properties": {
      "message": {
        "properties":{
          "timestamp_received":{
            "type":"date"
          }
        }
      }
    }
  }
}

###
POST {{baseUrl}}/sample-index/_doc/1
Content-Type: application/x-ndjson

{
    "message" : {
      "timestamp_received" : "1705642934886"
    }
}

###
POST {{baseUrl}}/_plugins/_sql
Content-Type: application/x-ndjson

{
  "query" : "SELECT message.timestamp_received FROM sample-index"
}

###
DELETE {{baseUrl}}/ltjin-test1

###
PUT {{baseUrl}}/ltjin-test1
Content-Type: application/x-ndjson

{
  "mappings": {
    "properties": {
      "name": {
        "type": "keyword"
      },
      "test.occupation": {
        "type": "text"
      },
      "country": {
        "type": "text"
      },
      "salary": {
        "type": "integer"
      },
      "year": {
        "type": "integer"
      },
      "month": {
        "type": "integer"
      }
    }
  }
}

###
POST {{baseUrl}}/_bulk
Content-Type: application/x-ndjson

{"index":{"_index" : "ltjin-test1","_id":"1"}}
{"name":"Jake","test.occupation":"Engineer","country":"England","salary":100000,"year":2023,"month":4}

###
GET  {{baseUrl}}/ltjin-test1


###
GET  {{baseUrl}}/ltjin-test1/_search

###
GET {{baseUrl}}/ltjin-test1/_search
Content-Type: application/x-ndjson

{
  "fields": [
    "test.occupation"
  ]
}