version: "3.8"

services:
  opensearch-a:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-a
    environment:
      - cluster.name=cluster_a
      - node.name=opensearch-a
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    ports:
      - "9200:9200"   # REST
      - "9300:9300"   # transport (CCS uses this)
    networks: [opensearch-net]

  opensearch-b:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch-b
    environment:
      - cluster.name=cluster_b
      - node.name=opensearch-b
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    ports:
      - "19200:9200"  # REST
      - "19300:9300"  # transport
    networks: [opensearch-net]

networks:
  opensearch-net: