@baseUrl = http://localhost:9200

### Get all indices
GET {{baseUrl}}/_cat/indices


### Get all indices
GET {{baseUrl}}/_cat/shards

###
DELETE {{baseUrl}}/hits_startree

###
GET {{baseUrl}}/hits_startree/



### Test analyzer with the sample log text
GET {{baseUrl}}/log_analysis/_analyze
Content-Type: application/x-ndjson

{
  "analyzer": "log_analyzer",
  "text": "logtype!=ws:access   error http 100"
}

### Insert sample document
POST {{baseUrl}}/log_analysis/_doc
{
  "message": "logtype=ws:access error"
}

### Search for documents with specific tokens
GET {{baseUrl}}/log_analysis/_search
{
  "query": {
    "match": {
      "message": "logtype"
    }
  }
}
