@baseUrl = http://localhost:9200

###
GET {{baseUrl}}/_cat/indices

### MAP PASS
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
    "query": "source=test"
}

### PASS
POST {{baseUrl}}/_plugins/_ppl/
Content-Type: application/x-ndjson

{
    "query": "source=test | fields _MAP.v"
}

### PASS
POST {{baseUrl}}/_plugins/_ppl/_explain
Content-Type: application/x-ndjson

{
    "query": "source=test | where _MAP.v=1"
}

### PASS
POST {{baseUrl}}/_plugins/_ppl/_explain
Content-Type: application/x-ndjson

{
    "query": "source=test | stats count by _MAP.v"
}



###
PUT {{baseUrl}}/test
Content-Type: application/x-ndjson

{
  "mappings": {
    "dynamic": "false",
    "properties": {
      "v" : {
        "type" : "integer"
      }
    }
  }
}

###
POST {{baseUrl}}/test/_bulk
Content-Type: application/x-ndjson

{"index": {"_id": 1}}
{"v": 1, "a": "1"}
{"index": {"_id": 2}}
{"v": 2, "b": "2"}
{"index": {"_id": 3}}
{"v": 3, "c": "3"}











###
PUT {{baseUrl}}/test
Content-Type: application/x-ndjson

{
  "mappings": {
    "dynamic": "false",
    "properties": {
      "@timestamp" : {
        "type" : "date",
        "format" : "yyyy-MM-dd HH:mm:ss" 
      }
    }
  }
}

###
POST {{baseUrl}}/test/_bulk
Content-Type: application/x-ndjson

{"index": {"_id": 1}}
{"timestamp" : "2025-05-01 05:49:00","v": 1, "a": "1"}
{"index": {"_id": 2}}
{"timestamp" : "2025-05-01 06:49:00","v": 2, "b": "2"}
{"index": {"_id": 3}}
{"timestamp" : "2025-05-01 07:49:00","v": 3, "c": "3"}

###
GET {{baseUrl}}/test

###
DELETE {{baseUrl}}/test