@baseUrl = http://localhost:9200

###
GET {{baseUrl}}/_cat/indices

###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
    "query": "source = http_logs | dedup 1 status | fields @timestamp, clientip, status, size | head 10"
}


###
POST {{baseUrl}}/_plugins/_ppl
Content-Type: application/x-ndjson

{
    "query": "source = http_logs "
}